### ISSUE TITLE
image

### ISSUE THREAD

**Issue by faizansidd97** [IamAli9/DM-PROJECT-PROPOSAL-.#54]
![image](https://user-images.githubusercontent.com/55597848/83179590-a87b0b80-a13b-11ea-86ae-209b892ffb17.png)

**Comment by faizansidd97** [comment]
Picture

**Comment by IamAli9** [comment]
What?

**Comment by faizansidd97** [comment]
Picture Is not uploading

**Comment by IamAli9** [comment]
Good Issue
